version: 4.29.0
markdownExploder: true
prd:
  prdFile: docs/prd/current/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture/current/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments:
  - docs/implementation/Implementation.md
  - docs/implementation/Bug_tracking.md
  - docs/implementation/workflow-status.md
  - docs/backend-rules.md
  - docs/frontend-rules.md
  - docs/debugging-guide.md
devLoadAlwaysFiles:
  - docs/architecture/current/project_structure.md
  - docs/architecture/current/UI_UX_doc.md
  - docs/implementation/Implementation.md
  - docs/implementation/Bug_tracking.md
  - docs/backend-rules.md
  - docs/frontend-rules.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
projectType: brownfield-fullstack
currentPhase: production-integration
targetRelease: Q4-2025
